### ISSUE TITLE
Add a wiki: Akudama Drive

### ISSUE THREAD

**Issue by KevinPayravi** [IndieWikiBuddy/indie-wiki-buddy-data#103]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://akudamadrive.fandom.com
Link to destination (independent) wiki: https://akudamadrive.miraheze.org

**Comment by Elaeagnifolia** [comment]
Very small, niche wikis (~40 content pages on both the origin and destination wiki). Otherwise, the destination wiki does indeed have more activity over the Fandom one.

**Comment by jaj-a11y** [comment]
Hello! I was the person who submitted this Wiki, and I created a Github account since. I hope this is appropriate to add, but since it was mentioned that maybe the Wiki is too niche, I want to offer the additional information that the Fandom Wiki is currently locked and not being updated at all. This was my doing, as the former Fandom Wiki admin. 

This matches the "_The destination wiki should be of decent quality, ideally matching (or exceeding) the quality and size of the origin wiki. While we want to support all independent wikis, we also want extension users to be directed to wikis where they can find what they are looking for._" criterion, as the Miraheze Wiki is active and now has more, more recent, and more accurate information than the Fandom one!

We are indeed a niche community, but Akudama Drive was extremely popular in the West when it came out and has a fairly large potential for casual fans/readers, despite the small potential for current editors now that the anime is 3 years old.

I'm not super familiar with all possible ways for Wikis to be added, and if this Wiki is too small to be added, I understand. Thank you to everyone who works on this very helpful extension - I'm trying everything to get my chance, since the Miraheze Wiki doesn't appear in Google search results for let's say, Akudama Drive characters.

**Comment by KevinPayravi** [comment]
@jaj-a11y Thanks for the details! Sounds good to me - will include Akudama Drive in the next update.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/a6c9e8071556d5089cc0daf791aa0dbbe45501f8

**Comment by jaj-a11y** [comment]
I'm so glad to hear it - thank you very much!
